$(function(){
	$("#one").hover(function(){
		$("#bootone").slideUp();
	},function(){
		$("#bootone").slideDown();
	})
})

$(function(){
	$("#two").hover(function(){
		$("#boottwo").slideUp();
	},function(){
		$("#boottwo").slideDown();
	})
})

$(function(){
	$("#three").hover(function(){
		$("#bootthree").slideUp();
	},function(){
		$("#bootthree").slideDown();
	})
})

$(function(){
	$("#four").hover(function(){
		$("#bootfour").slideUp();
	},function(){
		$("#bootfour").slideDown();
	})
})

$(function(){
	$("#butone").hover(function(){
		$(this).addClass("change");
		$("#hrefone").css("color","white");
	},function(){
		$(this).removeClass("change");
		$("#hrefone").css("color","#95bfec");
	})
})
$(function(){
	$("#buttwo").hover(function(){
		$(this).addClass("change");
		$("#hreftwo").css("color","white");
	},function(){
		$(this).removeClass("change");
		$("#hreftwo").css("color","#95bfec");
	})
})
$(function(){
	$("#butthree").hover(function(){
		$(this).addClass("change");
		$("#hrefthree").css("color","white");
	},function(){
		$(this).removeClass("change");
		$("#hrefthree").css("color","#95bfec");
	})
})
$(function(){
	$("#butfour").hover(function(){
		$(this).addClass("change");
		$("#hreffour").css("color","white");
	},function(){
		$(this).removeClass("change");
		$("#hreffour").css("color","#95bfec");
	})
})
